vim.cmd("set showmatch")
vim.cmd("set mouse=v")
vim.cmd("set hlsearch")
vim.cmd("set incsearch")
vim.cmd("set autoindent")
vim.cmd("set number")
vim.cmd("set termguicolors")
vim.cmd("set cursorline")
vim.cmd("set wildmode=list:longest,list:full")
vim.cmd("filetype plugin indent on")
vim.cmd("syntax on")
vim.cmd("set mouse=a")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("filetype plugin on")
vim.cmd("set ttyfast")
vim.cmd("set spell")
vim.cmd("set noswapfile")
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.g.mapleader = " "

vim.keymap.set("v", "<C-c>", '"+y')
vim.keymap.set("n", "<leader>v", '"*p')
vim.keymap.set("n", "<C-Up>", "<C-W>k")
vim.keymap.set("n", "<C-Left>", "<C-W>h")
vim.keymap.set("n", "<C-Right>", "<C-W>l")
vim.keymap.set("n", "<C-Down>", "<C-W>j")
