[[manager.append_keymap]]
on = "!"
run = 'shell --interactive "" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.append_keymap]]
on = "<C-n>"
run = '''
    shell --confirm 'dragon -x -i -T "$1"'
    <Enter>
'''

[[manager.append_keymap]]
on = "<C-e>"
run = '''
    shell --confirm '
        paths=$(forp in "$@"; do echo "$p"; done | paste -s -d,
        quoted="'\'$paths\''"
        thunderbird -compose "attachment=$quoted"
    ' <Enter>
'''

[[manager.append_keymap]]
on = "E"
run = '''
    shell --block --confirm 'sudo eject $(findmnt -n -o source "$@")'
'''
desc = "Eject the usb drive from mount point"

[[manager.append_keymap]]
on = ["g", "r"]
run = "cd /"
desc = "Go to root"

[[manager.append_keymap]]
on = ["g", "u"]
run = 'cd /run/media/"$USER"'
desc = "Go to removable devices directory"

[[manager.append_keymap]]
on = "F"
run = "find"

[[manager.append_keymap]]
on = "&"
run = "tab_switch 0"
desc = "Switch to the first tab" 

[[manager.append_keymap]]
on = "é"
run = "tab_switch 1"
desc = "Switch to the second tab" 

[[manager.append_keymap]]
on = '"'
run = "tab_switch 2"
desc = "Switch to the third tab" 

[[manager.append_keymap]]
on = "'"
run = "tab_switch 3"
desc = "Switch to the fourth tab" 

[[manager.append_keymap]]
on = "("
run = "tab_switch 4"
desc = "Switch to the fith tab" 

[[manager.append_keymap]]
on = "-"
run = "tab_switch 5"
desc = "Switch to the sixth tab" 

[[manager.append_keymap]]
on = "è"
run = "tab_switch 6"
desc = "Switch to the seventh tab" 

[[manager.append_keymap]]
on = "_"
run = "tab_switch 7"
desc = "Switch to the eight tab" 

[[manager.append_keymap]]
on = "ç"
run = "tab_switch 8"
desc = "Switch to the ninth tab" 
